# Generated by Django 5.2.17 on 2026-09-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('supplier_charges', 'Supplier charges'), ('freight_miami', 'Freight to Miami'), ('forwarder', 'Forwarder and Miami warehouse'), ('freight_intl', 'International freight'), ('insurance', 'Cargo insurance'), ('customs_broker', 'Customs broker'), ('duties', 'Duties and import taxes'), ('port_charges', 'Port charges'), ('local_delivery', 'Local delivery in Venezuela'), ('documents', 'Documents and inspections'), ('bank', 'Bank and LC fees'), ('commission', 'Commissions'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='fixed', max_length=10)),
                ('percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('percent_base', models.CharField(blank=True, choices=[('goods_cost', 'Goods cost'), ('sell_value', 'Sell value'), ('cif_value', 'CIF value')], max_length=20)),
                ('estimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('client_treatment', models.CharField(blank=True, choices=[('included', 'Built into item prices'), ('separate', 'Separate line on quote and invoice'), ('absorbed', 'Our cost only')], max_length=10)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_ref', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('overrun_acknowledged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_costs', to='deals.deal')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='logistics.shipment')),
                ('supplier_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='logistics.supplierorder')),
            ],
            options={
                'db_table': 'deal_costs',
                'ordering': ['deal_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DealCostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_treatment', models.CharField(choices=[('included', 'Built into item prices'), ('separate', 'Separate line on quote and invoice'), ('absorbed', 'Our cost only')], max_length=10)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_settings', to='deals.deal')),
            ],
            options={
                'db_table': 'deal_cost_settings',
            },
        ),
    ]
