# Generated by Django 5.2.17 on 2026-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcost',
            name='basis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dealcost',
            name='breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dealcost',
            name='weight_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dealcost',
            name='weight_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
