# Generated by Django 5.2.17 on 2026-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_dealcost_basis_dealcost_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcostsettings',
            name='target_margin',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dealcostsettings',
            name='transit_days',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dealcostsettings',
            name='default_treatment',
            field=models.CharField(blank=True, choices=[('included', 'Built into item prices'), ('separate', 'Separate line on quote and invoice'), ('absorbed', 'Our cost only')], max_length=10),
        ),
    ]
