# Generated by Django 5.2.17 on 2026-10-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_dealcostsettings_target_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcost',
            name='volumetric_divisor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
