# Generated by Django 5.2.17 on 2026-10-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_dealcost_volumetric_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcost',
            name='charge_mode',
            field=models.CharField(blank=True, default='weight', max_length=10),
        ),
    ]
