# Generated by Django 5.2.17 on 2026-09-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('deals', '0002_initial'),
        ('finance', '0001_initial'),
        ('logistics', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='clients.client')),
                ('deal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='deals.deal')),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='suppliers.supplier')),
                ('supplier_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='logistics.supplierorder')),
            ],
            options={
                'db_table': 'payment_plans',
            },
        ),
    ]
