# Generated by Django 5.2.17 on 2026-10-08 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoice',
            name='credits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='finance.clientinvoice'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit', 'Credit note')], default='invoice', max_length=10),
        ),
    ]
