# Generated by Django 6.1.1 on 2026-09-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mime_type', models.CharField(default='image/png', max_length=100)),
                ('data', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(max_length=200)),
                ('sequence', models.IntegerField(default=1)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('receiver_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
            options={
                'db_table': 'delivery_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delivered', models.DecimalField(decimal_places=4, max_digits=18)),
                ('deal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.dealitem')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.deliverynote')),
            ],
            options={
                'db_table': 'delivery_note_items',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=200, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('web_view_link', models.URLField(max_length=1000)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('Quote', 'Quote'), ('PO', 'PO'), ('Invoice', 'Invoice'), ('Delivery Note', 'Delivery Note'), ('Attachment', 'Attachment')], default='Attachment', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='clients.client')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='deals.deal')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(db_index=True, max_length=200)),
                ('qty_invoiced', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('deal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.dealitem')),
            ],
            options={
                'db_table': 'invoiced_items',
            },
        ),
    ]
