# Generated by Django 5.2.17 on 2026-09-29 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_initial'),
        ('quotes', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(error_messages={'unique': 'Another supplier order already uses this PO number.'}, max_length=60, unique=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to supplier'), ('confirmed', 'Confirmed by supplier'), ('ready', 'Ready to ship'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('incoterm', models.CharField(blank=True, max_length=20)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('ready_date', models.DateField(blank=True, null=True)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='deals.deal')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='suppliers.supplier')),
                ('supplier_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='quotes.supplierquote')),
            ],
            options={
                'db_table': 'supplier_orders',
                'ordering': ['deal_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(choices=[('to_miami', 'Supplier to Miami'), ('export', 'Miami to Venezuela'), ('delivery', 'Port to client'), ('direct', 'Supplier direct to client'), ('other', 'Other')], default='to_miami', max_length=20)),
                ('mode', models.CharField(choices=[('air', 'Air'), ('ocean', 'Ocean'), ('courier', 'Courier'), ('truck', 'Truck')], default='courier', max_length=20)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('forwarder', models.CharField(blank=True, max_length=200)),
                ('carrier', models.CharField(blank=True, max_length=200)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked'), ('in_transit', 'In transit'), ('customs', 'In customs'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('departed_date', models.DateField(blank=True, null=True)),
                ('arrived_date', models.DateField(blank=True, null=True)),
                ('packages', models.CharField(blank=True, max_length=200)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('freight_currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='deals.deal')),
                ('orders', models.ManyToManyField(blank=True, related_name='shipments', to='logistics.supplierorder')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['deal_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('part_number', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('deal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='deals.dealitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.supplierorder')),
            ],
            options={
                'db_table': 'supplier_order_items',
                'ordering': ['order_id', 'item_number', 'id'],
            },
        ),
    ]
