# Generated by Django 5.2.17 on 2026-10-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('credit_out', 'Credit moved out'), ('credit_in', 'Client credit applied')], default='payment', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_group',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
