# Generated by Django 6.1.1 on 2026-09-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('qty_reserved', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_items',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
