# Generated by Django 5.2.17 on 2026-09-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_initial'),
        ('quotes', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting reply'), ('replied', 'Quote received'), ('declined', 'Declined'), ('closed', 'Closed without reply')], default='awaiting', max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('sent_to', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('sent_date', models.DateField()),
                ('reply_by', models.DateField(blank=True, null=True)),
                ('replied_date', models.DateField(blank=True, null=True)),
                ('followup_count', models.IntegerField(default=0)),
                ('last_followup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='deals.deal')),
                ('deal_items', models.ManyToManyField(blank=True, related_name='rfqs', to='deals.dealitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='suppliers.supplier')),
                ('supplier_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='quotes.supplierquote')),
            ],
            options={
                'db_table': 'supplier_rfqs',
                'ordering': ['deal_id', '-sent_date', '-id'],
            },
        ),
    ]
