# Generated by Django 5.2.17 on 2026-10-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('number', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('superseded', 'Replaced by a newer version')], default='draft', max_length=20)),
                ('language', models.CharField(default='es', max_length=5)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('lines', models.JSONField(default=list)),
                ('charges', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_terms', models.CharField(blank=True, max_length=300)),
                ('incoterm', models.CharField(blank=True, max_length=20)),
                ('delivery_point', models.CharField(blank=True, max_length=200)),
                ('delivery_time', models.CharField(blank=True, max_length=200)),
                ('client_ref', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('followup_count', models.IntegerField(default=0)),
                ('last_followup_date', models.DateField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_quotes', to='deals.deal')),
            ],
            options={
                'db_table': 'client_quotes',
                'ordering': ['deal_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ClientPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('received_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('attachment_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received, to process'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('checks', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_pos', to='deals.deal')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='clientquotes.clientquote')),
            ],
            options={
                'db_table': 'client_purchase_orders',
                'ordering': ['deal_id', '-received_date', '-id'],
            },
        ),
    ]
