# Generated by Django 5.2.17 on 2026-10-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientquotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpo',
            name='lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
