# Generated by Django 6.1.1 on 2026-09-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ref', models.CharField(blank=True, max_length=200)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('incoterm', models.CharField(blank=True, max_length=20)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='deals.deal')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'supplier_quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('deal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.dealitem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.supplierquote')),
            ],
            options={
                'db_table': 'supplier_quote_items',
                'unique_together': {('quote', 'deal_item')},
            },
        ),
    ]
