# Generated by Django 5.2.17 on 2026-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquoteitem',
            name='lead_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquoteitem',
            name='unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
