# Generated by Django 5.2.17 on 2026-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_supplierquoteitem_lead_time_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierquoteitem',
            name='unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=16, null=True),
        ),
    ]
