# Generated by Django 6.1.1 on 2026-09-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('description', models.TextField()),
                ('part_number', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model_name', models.CharField(blank=True, db_column='model', max_length=200)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('margin_pct', models.DecimalField(decimal_places=4, default=0.15, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('is_split_child', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'deal_items',
                'ordering': ['deal_id', 'item_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DealItemSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_awarded', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deal_item_splits',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('seller_entity', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Quoting', 'Quoting'), ('Negotiating', 'Negotiating'), ("Client's PO Received", "Client's PO Received"), ('PO Sent', 'PO Sent'), ('Invoiced', 'Invoiced'), ('Delivered', 'Delivered'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Quoting', max_length=50)),
                ('deal_status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('lost_reason', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('incoterm', models.CharField(blank=True, max_length=20)),
                ('port_location', models.CharField(blank=True, max_length=200)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('delivery_time', models.CharField(blank=True, max_length=200)),
                ('client_ref', models.CharField(blank=True, default='xxx-xxx', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deal_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
