# Generated by Django 6.1.1 on 2026-09-28 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='awarded_quote',
            field=models.ForeignKey(blank=True, db_column='awarded_quote_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_items', to='quotes.supplierquote'),
        ),
        migrations.AddField(
            model_name='dealitem',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, db_column='parent_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_children', to='deals.dealitem'),
        ),
        migrations.AddField(
            model_name='dealitemsplit',
            name='child_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_child_split', to='deals.dealitem'),
        ),
        migrations.AddField(
            model_name='dealitemsplit',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='deals.dealitem'),
        ),
        migrations.AddField(
            model_name='dealitemsplit',
            name='supplier_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.supplierquote'),
        ),
        migrations.AlterUniqueTogether(
            name='dealitemsplit',
            unique_together={('parent_item', 'supplier_quote')},
        ),
    ]
