# Generated by Django 5.2.17 on 2026-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealitem',
            name='margin_pct',
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=8),
        ),
    ]
